### ISSUE TITLE
possible misprint in correlation game

### ISSUE THREAD

**Issue by gabucsc** [ShinyEd/intro-stats#17]
The option to show the regression line with the easy and medium difficulty levels is reported in the 'Show:' section as 'Standard deviation line' instead of 'Regression line'.

**Comment by mine-cetinkaya-rundel** [comment]
This is not the regression line exactly. The slope of the line is calculated as follows:

https://github.com/ShinyEd/intro-stats/blob/44759a7c82b81ba926d981afe2833a89d36748fc/correlation_game/app.R#L139

The line cuts the ellipse in half, but doesn't exactly match up with the regression line of `y ~ x`.

**Comment by gabucsc** [comment]
Sorry to bother you, but this is exactly the slope of the regression line, if you write the regression line in its canonical form, see e.g. slide 19.21 at page 275 (pdf page 280) at http://system.educatt.com/libri/ebookRepository/boari-cantaluppi-web/BCslides.pdf

The book is in Italian, but notation in formula is common to English.

Kind regards,

Gabriele Cantaluppi






On 14 Nov 2020 at 12:12, Mine Cetinkaya-Rundel wrote:

>
> This is not the regression line exactly. The slope of the line is calculated as follows:
> https://github.com/ShinyEd/intro-stats/blob/44759a7c82b81ba926d981afe2833a89d36748fc/correl
> ation_game/app.R#L139
> The line cuts the ellipse in half, but doesn't exactly match up with the regression line of y ~ x.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.





Prof. Gabriele Cantaluppi
Professore Associato
Facoltà di Economia
Dipartimento di Scienze statistiche

gabriele.cantaluppi@unicatt.it
tel +39 02 7234 2492
fax +39 02 7234 3064

Università Cattolica del Sacro Cuore
Largo A. Gemelli 1, 20123 Milano
www.unicatt.it



[http://Static.unicatt.it/layout/img/layout/Iltuo5x1000bottone.gif]

www.unicatt.it/5permille/<http://www.unicatt.it/5permille/>

**Comment by mine-cetinkaya-rundel** [comment]
Does the formula in the book say the slope of the regression line is correlation times the ratio of the two standard deviations?

**Comment by gabucsc** [comment]
Exactly.

\sigma is sqrt((n-1)/n) * sd

but sqrt((n-1)/n) at numerator and denominator will simplify.

If you are interested, you can find an English version of the book by me and Giuseppe Boari at
https://www.ibs.it/notes-of-descriptive-statistics-probability-ebook-inglese-gabriele-cantaluppi-giuseppe-boari/e/9788893353144

Unfortunately the English version is not free. We have not royalties. The revenue 6Euro is to EDUCatt, the foundation of our university that grants scholarships to our students.

English is also not perfect, since I translated the whole book in only one week for another R course.

Best regards,

Gabriele Cantaluppi

On 14 Nov 2020 at 13:11, Mine Cetinkaya-Rundel wrote:

>
> Does the formula in the book say the slope of the regression line is correlation times the ratio of
> the two standard deviations?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.





Prof. Gabriele Cantaluppi
Professore Associato
Facoltà di Economia
Dipartimento di Scienze statistiche

gabriele.cantaluppi@unicatt.it
tel +39 02 7234 2492
fax +39 02 7234 3064

Università Cattolica del Sacro Cuore
Largo A. Gemelli 1, 20123 Milano
www.unicatt.it



[http://Static.unicatt.it/layout/img/layout/Iltuo5x1000bottone.gif]

www.unicatt.it/5permille/<http://www.unicatt.it/5permille/>

**Comment by mine-cetinkaya-rundel** [comment]
Right, this line is using the sign of the correlation (not the magnitude) multiplied by the ratio of the standard deviations. 

We could also show the actual regression line if that's desirable. I don't quite remember the reasoning behind why we showed this line as opposed to the regression line.

**Comment by gabucsc** [comment]
That's ok. I missed that only the sign of correlation was present in your line of code.

Maybe, when plotting also ellipses, the regression line would differ, as you stated, from the ellipsis axis and this would not be 'nice to see'.

The regression line, in order to guess the sign of correlation. would maybe more intuitive at a descriptive statistic level, where the joint bivariate normal distribution is not introduced.

The current 'standard deviation line' is maybe a bit difficult to interpret, 'ellipsis main axis' maybe would be better.

If possible, I suggest to complete with both features:
- regression line, that will help students at descriptive statistics level,
- ellipsis main axis, that will help students at multivariate statistics level in remembering the difference between the two formulae.



On 14 Nov 2020 at 13:43, Mine Cetinkaya-Rundel wrote:

>
> Right, this line is using the sign of the correlation (not the magnitude) multiplied by the ratio of the
> standard deviations.
> We could also show the actual regression line if that's desirable. I don't quite remember the
> reasoning behind why we showed this line as opposed to the regression line.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.





Prof. Gabriele Cantaluppi
Professore Associato
Facoltà di Economia
Dipartimento di Scienze statistiche

gabriele.cantaluppi@unicatt.it
tel +39 02 7234 2492
fax +39 02 7234 3064

Università Cattolica del Sacro Cuore
Largo A. Gemelli 1, 20123 Milano
www.unicatt.it



[http://Static.unicatt.it/layout/img/layout/Iltuo5x1000bottone.gif]

www.unicatt.it/5permille/<http://www.unicatt.it/5permille/>

**Comment by gabucsc** [comment]
My intuition was wrong (I am a bit tired): you are not plotting the main axis of the ellipse, since e.g. if rho=0, this would be horizontal shaped; therefore I can guess that sign(rho) sd_y / sd_x
was designated to give some hint cutting the ellipse in half but not helping too much students;

[graphic]

when rho increases the line seems to be close to the main axis of the ellipse; therefore I have no suggestion for the name of the line currently appearing on the graph.


On 14 Nov 2020 at 23:38, ShinyEd/intro-stats , ShinyEd wrote:

> That's ok. I missed that only the sign of correlation was present in your line of
> code.
>
> Maybe, when plotting also ellipses, the regression line would differ, as you
> stated, from the ellipsis axis and this would not be 'nice to see'.
>
> The regression line, in order to guess the sign of correlation. would maybe more
> intuitive at a descriptive statistic level, where the joint bivariate normal distribution
> is not introduced.
>
> The current 'standard deviation line' is maybe a bit difficult to interpret, 'ellipsis
> main axis' maybe would be better.
>
> If possible, I suggest to complete with both features:
> - regression line, that will help students at descriptive statistics level,
> - ellipsis main axis, that will help students at multivariate statistics level in
> remembering the difference between the two formulae.
>
>
>
> On 14 Nov 2020 at 13:43, Mine Cetinkaya-Rundel wrote:
>
> >
> > Right, this line is using the sign of the correlation (not the magnitude) multiplied
> by the ratio of the
> > standard deviations.
> > We could also show the actual regression line if that's desirable. I don't quite
> remember the
> > reasoning behind why we showed this line as opposed to the regression line.
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
>
>





Prof. Gabriele Cantaluppi
Professore Associato
Facoltà di Economia
Dipartimento di Scienze statistiche

gabriele.cantaluppi@unicatt.it
tel +39 02 7234 2492
fax +39 02 7234 3064

Università Cattolica del Sacro Cuore
Largo A. Gemelli 1, 20123 Milano
www.unicatt.it



[http://Static.unicatt.it/layout/img/layout/Iltuo5x1000bottone.gif]

www.unicatt.it/5permille/<http://www.unicatt.it/5permille/>
